SELECT 
    fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fo.AMOUNT*fp.PRICE) 'TOTAL_SALES'
FROM FOOD_PRODUCT fp, FOOD_ORDER fo
WHERE fp.PRODUCT_ID = fo.PRODUCT_ID 
    AND DATE_FORMAT(fo.PRODUCE_DATE, "%Y-%m") = "2022-05" 
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID
