SELECT 
    fd.CATEGORY, cp.MAX_PRICE, fd.PRODUCT_NAME
FROM FOOD_PRODUCT fd, 
(
    SELECT CATEGORY, MAX(PRICE) 'MAX_PRICE' 
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) cp
WHERE fd.CATEGORY in ('과자', '국', '김치', '식용유')
AND fd.PRICE = cp.MAX_PRICE
GROUP BY fd.CATEGORY
ORDER BY fd.PRICE DESC
