SELECT 
    ugu.USER_ID, ugu.NICKNAME, SUM(ugb.PRICE) 'TOTAL_SALES'
FROM USED_GOODS_BOARD ugb, USED_GOODS_USER ugu
WHERE ugb.WRITER_ID = ugu.USER_ID 
    AND ugb.STATUS = 'DONE'
GROUP BY ugu.USER_ID
HAVING SUM(ugb.PRICE) >= 700000
ORDER BY SUM(ugb.PRICE);
