SELECT b.CATEGORY 'CATEGORY',
      SUM(bs.SALES) 'TOTAL_SALES'
FROM BOOK b, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID
      AND bs.SALES_DATE LIKE ("2022-01%")
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;
